export type PrivacyLanguage = "en" | "de";
export interface NoticeSection {
  id: string;
  en: { title: string; paragraphs: string[] };
  de: { title: string; paragraphs: string[] };
}

export const noticeLabels = {
  en: {
    title: "Privacy Notice", description: "How Detoura handles personal information during Limited Beta.",
    language: "Language / Sprache", contents: "In this notice", effective: "Effective date",
    draft: "Development draft — legal configuration and approval are incomplete. This notice is not ready for production.",
    unavailable: "This Privacy Notice is not yet available. Detoura’s Limited Beta privacy information is awaiting final approval.",
    missing: "Not yet configured in this development draft.", home: "Detoura home",
  },
  de: {
    title: "Datenschutzhinweise", description: "Wie Detoura während der Limited Beta personenbezogene Informationen verarbeitet.",
    language: "Sprache / Language", contents: "In diesen Hinweisen", effective: "Gültig ab",
    draft: "Entwicklungsentwurf — rechtliche Angaben und Freigaben sind unvollständig. Diese Hinweise sind noch nicht für die Veröffentlichung bereit.",
    unavailable: "Diese Datenschutzhinweise sind noch nicht verfügbar. Die Datenschutzinformationen für Detouras Limited Beta warten auf die abschließende Freigabe.",
    missing: "In diesem Entwicklungsentwurf noch nicht konfiguriert.", home: "Detoura Startseite",
  },
};

// Paired sections keep English and German within the same approved scope.
export const noticeSections: NoticeSection[] = [
  { id: "controller",
    en: { title: "Controller", paragraphs: ["The controller and privacy contact for Detoura are listed below."] },
    de: { title: "Verantwortlicher", paragraphs: ["Der Verantwortliche und der Datenschutzkontakt für Detoura sind nachfolgend aufgeführt."] } },
  { id: "scope",
    en: { title: "Scope", paragraphs: ["This notice covers the Detoura Limited Beta website, accounts, journey planning and booking services."] },
    de: { title: "Geltungsbereich", paragraphs: ["Diese Hinweise gelten für die Website, Konten, Reiseplanung und Buchungsdienste der Detoura Limited Beta."] } },
  { id: "account",
    en: { title: "Account and authentication", paragraphs: ["We process account and authentication information to provide and secure your Detoura account. Passwords are stored as hashes, not as plaintext. Session and security cookies support sign-in and protect requests."] },
    de: { title: "Konto und Authentifizierung", paragraphs: ["Wir verarbeiten Konto- und Authentifizierungsinformationen, um Ihr Detoura-Konto bereitzustellen und abzusichern. Passwörter werden als Hashwerte gespeichert, nicht im Klartext. Sitzungs- und Sicherheitscookies unterstützen die Anmeldung und schützen Anfragen."] } },
  { id: "google",
    en: { title: "Google Sign-In", paragraphs: ["Google Sign-In is optional. Google account information is used for authentication, account linking and security, not for marketing profiling in the Beta."] },
    de: { title: "Anmeldung mit Google", paragraphs: ["Die Anmeldung mit Google ist optional. Google-Kontoinformationen werden zur Authentifizierung, Kontoverknüpfung und Sicherheit verwendet, nicht zur Erstellung von Marketingprofilen in der Beta."] } },
  { id: "planning",
    en: { title: "Search and journey planning", paragraphs: ["We may use your origin, dates or flexibility, budget, traveller count and preferences to provide the travel planning you request. Optional behavioural analytics is not enabled.", "Non-sensitive journey drafts may be stored temporarily on your device for at most 30 days from creation of that draft generation. Restoring a draft does not extend its expiry. Drafts are planning estimates; booking, payment and financial-document status comes from the server.", "Saved recommendations and your theme preference are separate browser settings. Saved recommendations remain until you remove them or clear browser storage; the 30-day draft limit does not apply to them. Planning state may remain visible to others using the same browser after logout."] },
    de: { title: "Suche und Reiseplanung", paragraphs: ["Wir können Ihren Abreiseort, Reisedaten oder Flexibilität, Ihr Budget, die Anzahl der Reisenden und Ihre Präferenzen verwenden, um die gewünschte Reiseplanung bereitzustellen. Optionale Verhaltensanalysen sind nicht aktiviert.", "Reiseentwürfe ohne sensible Informationen können vorübergehend auf Ihrem Gerät gespeichert werden, höchstens 30 Tage ab Erstellung der jeweiligen Entwurfsversion. Das Wiederherstellen verlängert die Frist nicht. Entwürfe sind Planungsschätzungen; der Status von Buchungen, Zahlungen und Finanzdokumenten stammt vom Server.", "Gespeicherte Reisevorschläge und Ihre Darstellungseinstellung sind separate Browsereinstellungen. Gespeicherte Vorschläge bleiben bestehen, bis Sie sie entfernen oder den Browserspeicher löschen; die 30-Tage-Frist für Entwürfe gilt für sie nicht. Planungsdaten können nach der Abmeldung für andere Personen im selben Browser sichtbar bleiben."] } },
  { id: "travellers",
    en: { title: "Booking and traveller information", paragraphs: ["Booking may require traveller details needed by the relevant travel supplier. Detoura minimizes persistent storage of sensitive traveller information. Required information may be transmitted to Duffel and relevant airlines or travel suppliers.", "Detoura Limited Beta does not intentionally collect health information, religious dietary requirements or other special-category traveller information."] },
    de: { title: "Buchung und Angaben zu Reisenden", paragraphs: ["Für eine Buchung können Angaben zu Reisenden erforderlich sein, die der jeweilige Reiseanbieter benötigt. Detoura minimiert die dauerhafte Speicherung sensibler Angaben zu Reisenden. Erforderliche Informationen können an Duffel und die betreffenden Fluggesellschaften oder Reiseanbieter übermittelt werden.", "Detoura Limited Beta erhebt nicht gezielt Gesundheitsinformationen, religiöse Ernährungsanforderungen oder andere besondere Kategorien personenbezogener Daten von Reisenden."] } },
  { id: "payments",
    en: { title: "Payments", paragraphs: ["Stripe provides payment processing. Detoura does not store full card numbers or CVC codes. Certain transaction records may remain after account deletion where an applicable retained purpose exists."] },
    de: { title: "Zahlungen", paragraphs: ["Stripe übernimmt die Zahlungsabwicklung. Detoura speichert keine vollständigen Kartennummern oder CVC-Codes. Bestimmte Transaktionsdaten können nach einer Kontolöschung erhalten bleiben, wenn ein entsprechender Aufbewahrungszweck besteht."] } },
  { id: "travel-providers",
    en: { title: "Travel providers", paragraphs: ["Detoura currently uses Duffel for travel inventory and booking. Relevant airlines and travel suppliers receive booking information where necessary to provide the requested services."] },
    de: { title: "Reiseanbieter", paragraphs: ["Detoura nutzt derzeit Duffel für Reiseangebote und Buchungen. Die betreffenden Fluggesellschaften und Reiseanbieter erhalten Buchungsinformationen, soweit dies für die gewünschten Leistungen erforderlich ist."] } },
  { id: "email",
    en: { title: "Transactional email", paragraphs: ["Service emails may include account security, password reset, booking and recovery communications as applicable. Resend is used for transactional email. Marketing email is disabled."] },
    de: { title: "Transaktions-E-Mails", paragraphs: ["Service-E-Mails können je nach Anlass die Kontosicherheit, das Zurücksetzen von Passwörtern, Buchungen und die Wiederherstellung von Buchungsabläufen betreffen. Resend wird für Transaktions-E-Mails verwendet. Marketing-E-Mails sind deaktiviert."] } },
  { id: "financial-documents",
    en: { title: "Financial documents", paragraphs: ["Account deletion does not automatically delete financial or accounting records that must be retained. Retention is specific to the record category; the entire booking does not have one blanket statutory retention period."] },
    de: { title: "Finanzdokumente", paragraphs: ["Eine Kontolöschung löscht nicht automatisch Finanz- oder Buchhaltungsunterlagen, die aufbewahrt werden müssen. Die Aufbewahrung richtet sich nach der Datenkategorie; es gilt keine einheitliche gesetzliche Frist für die gesamte Buchung."] } },
  { id: "security",
    en: { title: "Security and operational data", paragraphs: ["Limited technical data may be processed for operation, security, abuse prevention and diagnostics. The Product/Ops Limited Beta policy limits ordinary identifiable operational logs to at most 14 days, subject to documented exceptions such as an active security incident. Deployment operations are responsible for enforcing this policy."] },
    de: { title: "Sicherheit und Betriebsdaten", paragraphs: ["Begrenzte technische Daten können für den Betrieb, die Sicherheit, die Missbrauchsprävention und die Fehlerdiagnose verarbeitet werden. Die Produkt-/Betriebsrichtlinie der Limited Beta begrenzt gewöhnliche personenbeziehbare Betriebsprotokolle auf höchstens 14 Tage, vorbehaltlich dokumentierter Ausnahmen wie eines aktiven Sicherheitsvorfalls. Für die Umsetzung ist der Deployment-Betrieb verantwortlich."] } },
  { id: "analytics",
    en: { title: "Analytics, advertising and marketing", paragraphs: ["Optional product analytics, marketing attribution and marketing tracking are disabled in Limited Beta. No optional measurement preference is needed for these disabled activities."] },
    de: { title: "Analyse, Werbung und Marketing", paragraphs: ["Optionale Produktanalysen, Marketingattribution und Marketingtracking sind in der Limited Beta deaktiviert. Für diese deaktivierten Aktivitäten ist keine optionale Messeinstellung erforderlich."] } },
  { id: "recipients",
    en: { title: "Recipients and service providers", paragraphs: ["Current provider categories include Google for optional authentication, Stripe for payments, Duffel and travel suppliers for booking, and Resend for transactional email.", "Some destination photographs load directly from Wikimedia. These requests disclose your IP address and browser metadata to the image host; the requests use a no-referrer policy. Photo-credit links open the named external website when selected."] },
    de: { title: "Empfänger und Dienstleister", paragraphs: ["Zu den derzeitigen Anbieterkategorien gehören Google für die optionale Authentifizierung, Stripe für Zahlungen, Duffel und Reiseanbieter für Buchungen sowie Resend für Transaktions-E-Mails.", "Einige Zielfotos werden direkt von Wikimedia geladen. Dabei erhält der Bildhost Ihre IP-Adresse und Browsermetadaten; die Anfragen verwenden eine No-Referrer-Richtlinie. Links zu Bildnachweisen öffnen bei Auswahl die genannte externe Website."] } },
  { id: "transfers",
    en: { title: "International transfers", paragraphs: ["Processing by service providers may involve international transfers. Applicable transfer mechanisms and safeguards are used where required. The arrangements depend on the service and destination of the transfer."] },
    de: { title: "Internationale Übermittlungen", paragraphs: ["Die Verarbeitung durch Dienstleister kann internationale Übermittlungen umfassen. Soweit erforderlich, werden anwendbare Übermittlungsmechanismen und Schutzmaßnahmen eingesetzt. Die Vorkehrungen hängen vom Dienst und vom Ziel der Übermittlung ab."] } },
  { id: "retention",
    en: { title: "Retention", paragraphs: ["Different categories have different retention rules. Temporary journey drafts last at most 30 days. Ordinary identifiable operational logs have a Product/Ops policy of at most 14 days, with documented exceptions. Account lifecycle data follows the account lifecycle.", "Financial, accounting and transaction records may require longer, category-specific retention. Data with no remaining purpose should be deleted or anonymized under the applicable policy."] },
    de: { title: "Aufbewahrung", paragraphs: ["Für verschiedene Datenkategorien gelten unterschiedliche Aufbewahrungsregeln. Vorübergehende Reiseentwürfe bestehen höchstens 30 Tage. Für gewöhnliche personenbeziehbare Betriebsprotokolle gilt eine Produkt-/Betriebsrichtlinie von höchstens 14 Tagen mit dokumentierten Ausnahmen. Daten des Kontolebenszyklus folgen dem Lebenszyklus des Kontos.", "Finanz-, Buchhaltungs- und Transaktionsdaten können eine längere, kategoriespezifische Aufbewahrung erfordern. Daten ohne verbleibenden Zweck sollen nach der anwendbaren Richtlinie gelöscht oder anonymisiert werden."] } },
  { id: "deletion",
    en: { title: "Account deletion", paragraphs: ["Deleting your Detoura account removes or disables the account and sign-in access. Certain booking, payment, financial or other legally retained historical records may remain where an applicable retention basis exists. Retained records are not used to recreate the deleted account or for marketing."] },
    de: { title: "Kontolöschung", paragraphs: ["Durch das Löschen Ihres Detoura-Kontos werden das Konto und der Anmeldezugang entfernt oder deaktiviert. Bestimmte historische Buchungs-, Zahlungs-, Finanz- oder andere rechtlich aufzubewahrende Daten können erhalten bleiben, wenn eine entsprechende Aufbewahrungsgrundlage besteht. Aufbewahrte Daten werden weder zur Wiederherstellung des gelöschten Kontos noch für Marketing verwendet."] } },
  { id: "export",
    en: { title: "Account-data export", paragraphs: ["Export account data provides the account information currently available through Detoura. The automated export is partial: account metadata, linked identities and booking IDs. It does not replace your statutory privacy rights. For a broader privacy request, use the privacy contact in this notice."] },
    de: { title: "Export von Kontodaten", paragraphs: ["Der Kontodatenexport stellt die derzeit über Detoura verfügbaren Kontoinformationen bereit. Der automatisierte Export ist teilweise: Kontometadaten, verknüpfte Identitäten und Buchungs-IDs. Er ersetzt Ihre gesetzlichen Datenschutzrechte nicht. Für eine umfassendere Datenschutzanfrage nutzen Sie den Datenschutzkontakt in diesen Hinweisen."] } },
  { id: "rights",
    en: { title: "Data-subject rights", paragraphs: ["Depending on the applicable law and circumstances, you may have rights of access, rectification, erasure, restriction, portability and objection, and to withdraw consent where processing relies on it. You may contact us about these rights. Requests are assessed under applicable requirements; not every request automatically results in deletion."] },
    de: { title: "Rechte betroffener Personen", paragraphs: ["Je nach anwendbarem Recht und Umständen können Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch sowie auf Widerruf einer Einwilligung bestehen, soweit die Verarbeitung darauf beruht. Sie können uns zu diesen Rechten kontaktieren. Anfragen werden nach den anwendbaren Anforderungen geprüft; nicht jede Anfrage führt automatisch zur Löschung."] } },
  { id: "authority",
    en: { title: "Supervisory authority", paragraphs: ["You may lodge a complaint with a competent data protection supervisory authority. The authority identified for Detoura is listed below."] },
    de: { title: "Aufsichtsbehörde", paragraphs: ["Sie können sich bei einer zuständigen Datenschutzaufsichtsbehörde beschweren. Die für Detoura benannte Behörde ist nachfolgend aufgeführt."] } },
  { id: "changes",
    en: { title: "Changes to the notice", paragraphs: ["This notice may be updated to reflect changes to the service or applicable requirements. The effective date identifies the current version."] },
    de: { title: "Änderungen dieser Hinweise", paragraphs: ["Diese Hinweise können aktualisiert werden, um Änderungen am Dienst oder an den anwendbaren Anforderungen abzubilden. Das Gültigkeitsdatum kennzeichnet die aktuelle Fassung."] } },
];
